name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Linting is in a separate job because golangci-lint is quite slow when
  # running it in cold-start mode.
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Install golangci-lint
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          echo "GOBIN: $(go env GOBIN) GOPATH: $(go env GOPATH)"
      - name: Run golangci-lint
        run: |
          $(go env GOPATH)/bin/golangci-lint --version || golangci-lint --version
          $(go env GOPATH)/bin/golangci-lint run ./... || golangci-lint run ./...

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.22.x
      - uses: actions/checkout@v2
      - run: make test
