name: docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker:
    strategy:
        matrix:
          go-version: [1.15.x]
          os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v2
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Login to Container Registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - 
        name: Build and Push container images
        run: |
          make docker